### ISSUE TITLE
Looking for some input

### ISSUE THREAD

**Issue by RZR7332** [hectorm/cetusguard#156]
Hi Hector,

First off, like and appreciate what you are doing here with this project - looks really cool and the approach seems better than the alternatives,

I have deployed CetusGuard a few days ago in conjunction with Smokeping and took snips from your examples, specifically the file for Traefik. I have a few questions, one I believe I did incorrectly, another more from a verification perspective:

- In your Traefik example, you bind both CetusGuard and Traefik to the same network (cetusguard); however I only noted afterwards that Traefik is bound to the loopback. In my case, I have bound Smokeping and CetusGuard to the same one network, but Smokeping listens on all interfaces. Would the correct approach here have been to replicate your other examples, and bind Smokeping to both public and private, while binding CetusGuard to private only?
- Is there a way to validate/test if the proxying is working as expected? Everything appears to be operational but I would like to test to see if calls are indeed being filtered.

Thanks for any input, appreciate your work!

**Comment by hectorm** [comment]
Hi, would it be correct to either have a public and a private network, assign CetusGuard only to the private network and SmokePing on both networks or have a single network and let SmokePing listen on all interfaces. CetusGuard only needs to communicate with the Docker daemon and does not use or need public Internet access. The examples provided are only to demonstrate the use of CetusGuard and are intended to be as simple as possible.

You can check if the filtering is working correctly by setting the variable `CETUSGUARD_LOG_LEVEL` to `7`. This will log the requests and whether they are allowed or denied (by default only denied requests are shown).

**Comment by RZR7332** [comment]
Is it considered normal to see nothing logged, beyond the startup logs? I have already set the level to 7, perhaps Smokeping just does not interact with the daemon.

**Comment by hectorm** [comment]
I have not used SmokePing, but I suspect that it does not use the Docker daemon.
