### ISSUE TITLE
Dozzle 

### ISSUE THREAD

**Issue by zleppy** [hectorm/cetusguard#164]
Trying to run dozzle (https://dozzle.dev) via cetusguard and i keep getting 

# Cetusguard debug logs 
cetusguard  | DEBUG: 2023/10/26 20:12:24 allowed request: GET /v1.43/containers/json
cetusguard  | DEBUG: 2023/10/26 20:12:24 allowed request: GET /v1.43/containers/a3eba8d901df/json
cetusguard  | DEBUG: 2023/10/26 20:12:24 allowed request: GET /v1.43/containers/a3eba8d901df/logs
cetusguard  | DEBUG: 2023/10/26 20:12:24 connection hijack
cetusguard  | ERROR: 2023/10/26 20:12:24 body is not writable

# Dozzle debug logs
log  | level=debug msg="streaming logs for container" id=a3eba8d901df since= stdType=all
log  | level=debug msg="streaming logs for container" id=a3eba8d901df since= stdType=all

everytime i try to open the log screen.

**Comment by hectorm** [comment]
Interesting, I'll check it out in the next few days, thanks for reporting!

**Comment by hectorm** [comment]
I've reproduced the issue locally and after some testing I think it's fixed now.

Can you try using the `docker.io/hectorm/cetusguard:master` tag?

**Comment by zleppy** [comment]
Yupp! works like a charm now!

**Comment by hectorm** [comment]
Great, I just released a new version with this fix.
